[package]
name = "redis-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.redis]
git = "https://github.com/mitsuhiko/redis-rs.git"
